### ISSUE TITLE
Imposible use with fastify@4.x

### ISSUE THREAD

**Issue by rodmoreno** [fastify/fastify-soap-client#56]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.1

### Plugin version

1.0.0

### Node.js version

16.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

I received the error: `fastify-plugin: fastify-soap-client - expected '3.x' fastify version, '4.2.1' is installed`

### Steps to Reproduce

Start a new project with fastify@4.x and install @fastify/soap-client@1.0.0 and try to start the server

### Expected Behavior

Server start with normally

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by rodmoreno** [comment]
Sure I'll send a pull request to fix it
